app-template:
  controllers:
    main:
      imagePullSecrets:
        - name: acr-auth
      containers:
        main:
          image:
            repository: acrdmspro.azurecr.io/brandportal-angular
            tag: 8383
          env:
            _ENV: qc
            TZ: Asia/Saigon 
          probes:
            liveness:
              enabled: true
              custom: true
              type: http
              path: /
              port: 80
              spec:
                initialDelaySeconds: 0
                periodSeconds: 10
                timeoutSeconds: 5
                successThreshold: 1
                failureThreshold: 3
            readiness:
              enabled: true
              custom: true
              type: HTTP
              path: /
              port: 80
              spec:
                initialDelaySeconds: 0
                periodSeconds: 10
                timeoutSeconds: 5
                successThreshold: 1
                failureThreshold: 3
            startup:
              enabled: true
              custom: true
              type: http
              path: /
              port: 80
              spec:
                initialDelaySeconds: 0
                periodSeconds: 10
                timeoutSeconds: 5
                successThreshold: 1
                failureThreshold: 3
  service:
    main:
      ports:
        http:
          port: 80
          protocol: HTTP
  ingress:
    main:
      enabled: true
      className: nginx
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-http-issuer
      hosts:
        - host: &host test.bonbonshop.vn
          paths:
            - path: /
              pathType: Prefix
              service:
                name: main
                port: http
      tls:
        - hosts:
            - *host
          secretName: brandportal-angular-tls-certificate
